name: Polaris Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  polaris:
    runs-on: sh_window_sashi

    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Polaris Security Scan
        uses: blackduck-inc/black-duck-security-scan@main

        with:
          bridgecli_download_url: https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/4.5.0rc2/bridge-cli-bundle-4.5.0rc2-win64.zip

          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}

          polaris_assessment_types: SAST

          

          github_token: ${{ secrets.GITHUB_TOKEN }}

          polaris_prComment_enabled: true
          polaris_fixpr_enabled: true
          polaris_fixpr_filter_severities: HIGH
          polaris_fixpr_maxCount: 10
