name: CI-Polaris-Basic
"on":
  workflow_dispatch: null
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Polaris Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: SCA,SAST
